name: uni_payments
description: Uni Payments integrates various payment gateways for fast and easy transactions.
version: 0.0.5
homepage: https://github.com/NehilKoshiya/uni_payments/blob/master/example/lib/main.dart
repository: https://github.com/NehilKoshiya/uni_payments

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  razorpay_flutter: ^1.3.7
  flutter_paystack_max: ^1.0.4
  flutterwave_standard: ^1.0.8
  paytm_allinonesdk: ^1.2.5
  pay: ^2.0.0
  flutter_braintree: ^4.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.uni_payments
        pluginClass: UniPaymentsPlugin
      ios:
        pluginClass: UniPaymentsPlugin
