name: uni_payments
description: Uni Payments offers seamless integration for multiple payment gateways including Razorpay, Flutterwave, Google Pay, Paytm, Paystack, and PayPal ensuring a fast, easy and secure transaction process.
version: 2.0.0
homepage: https://github.com/NehilKoshiya/uni_payments/blob/master/example/lib/main.dart
repository: https://github.com/NehilKoshiya/uni_payments

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  razorpay_flutter: ^1.3.7
  flutter_paystack_max: ^1.0.4
  flutterwave_standard: ^1.0.8
  paytm_allinonesdk: ^1.2.5
  pay: ^2.0.0
  flutter_braintree: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.uni_payments
        pluginClass: UniPaymentsPlugin
      ios:
        pluginClass: UniPaymentsPlugin
      web:
        pluginClass: UniPaymentsWeb
        fileName: uni_payments_web.dart
