import 'dart:math';

import 'package:flutter/material.dart';
import 'package:uni_payments/uni_payments.dart';

/// Demo wrappers around `UniPayments` for each gateway shown in the UI.
///
/// Replace the placeholder keys / references with values from your own
/// dashboards before running. Every method returns a [PaymentResult] so the
/// UI can render a single response card no matter which gateway was used.
class PaymentDemos {
  PaymentDemos._();

  static const _customer = UniCustomer(
    name: 'Uni Demo',
    email: 'demo@unipayments.dev',
    phone: '9999999999',
  );

  static String _newReference() =>
      'ref_${DateTime.now().millisecondsSinceEpoch}_${Random().nextInt(9999)}';

  static Future<PaymentResult> razorpay() {
    return UniPayments.payWithRazorpay(
      keyId: 'YOUR_RAZORPAY_KEY_ID',
      amount: 25.00,
      businessName: 'Uni Payments',
      customer: _customer,
      description: 'Uni Payments demo charge',
      themeColor: const Color(0xFF6366F1),
    );
  }

  static Future<PaymentResult> stripe() {
    return UniPayments.payWithStripe(
      publishableKey: 'YOUR_STRIPE_PUBLISHABLE_KEY',
      // Created by your server via the PaymentIntents API.
      clientSecret: 'YOUR_PAYMENT_INTENT_CLIENT_SECRET',
      merchantDisplayName: 'Uni Payments Demo',
      merchantCountryCode: 'US',
      // Set to your registered Apple Pay merchant id to expose Apple Pay
      // in the sheet, e.g. 'merchant.com.example.unipayments'.
      applePayMerchantId: null,
    );
  }

  static Future<PaymentResult> paystack(BuildContext context) {
    return UniPayments.payWithPaystack(
      context: context,
      secretKey: 'YOUR_PAYSTACK_SECRET_KEY',
      amount: 25.00,
      customer: _customer,
      reference: _newReference(),
      callbackUrl: 'https://example.com/paystack/callback',
      currency: UniPaystackCurrency.usd,
    );
  }

  static Future<PaymentResult> paytm() {
    return UniPayments.payWithPaytm(
      merchantId: 'YOUR_MERCHANT_ID',
      orderId: _newReference(),
      // Generated by your backend via Paytm's initiateTransaction API.
      txnToken: 'YOUR_TXN_TOKEN',
      amount: 25.00,
      useStagingEnvironment: true,
    );
  }

  static Future<PaymentResult> flutterwave(BuildContext context) {
    return UniPayments.payWithFlutterwave(
      context: context,
      publicKey: 'YOUR_FLUTTERWAVE_PUBLIC_KEY',
      currency: 'NGN',
      amount: 25.00,
      customer: _customer,
      txRef: _newReference(),
      redirectUrl: 'https://example.com/flutterwave/return',
      testMode: true,
    );
  }

  static Future<PaymentResult> cashfree() {
    return UniPayments.payWithCashfree(
      // Both come from your backend's call to Cashfree's Orders API.
      orderId: _newReference(),
      paymentSessionId: 'YOUR_CASHFREE_PAYMENT_SESSION_ID',
      useStagingEnvironment: true,
    );
  }

  static Future<PaymentResult> phonepe() {
    return UniPayments.payWithPhonepe(
      merchantId: 'YOUR_MERCHANT_ID',
      flowId: _newReference(),
      // Base64-encoded JSON from your backend.
      requestBody: 'eyJtZXJjaGFudElkIjoiWU9VUl9NRVJDSEFOVF9JRCJ9',
      appSchema: 'unipaymentsdemo', // your iOS URL scheme
      useStagingEnvironment: true,
    );
  }

  static Future<PaymentResult> paypal() {
    return UniPayments.payWithPaypal(
      tokenizationKey: 'YOUR_BRAINTREE_TOKENIZATION_KEY',
      amount: 25.00,
      customer: _customer,
      currency: 'USD',
      countryCode: 'US',
    );
  }

  static Future<PaymentResult> googlePay(String configurationJson) {
    return UniPayments.payWithGooglePay(
      paymentConfigurationJson: configurationJson,
      lineItemLabel: 'Uni Payments demo',
      amount: 25.00,
    );
  }

  static Future<PaymentResult> applePay(String configurationJson) {
    return UniPayments.payWithApplePay(
      paymentConfigurationJson: configurationJson,
      lineItemLabel: 'Uni Payments demo',
      amount: 25.00,
    );
  }
}
